/*
 * This file was generated by FlintBuildTool.
 * Please do not edit/update this file manually.
 */

#include "flint_const_name_base.h"
#include "flint_const_name_base_hash_table.h"

const uint32_t baseConstUtf8HashIndex2[] = {
    2,
    (uint32_t)throwableClassName,
    (uint32_t)clazzFieldName,
};

const uint32_t baseConstUtf8HashIndex4[] = {
    1,
    (uint32_t)returnTypeFieldName,
};

const uint32_t baseConstUtf8HashIndex5[] = {
    1,
    (uint32_t)stringClassName,
};

const uint32_t baseConstUtf8HashIndex7[] = {
    2,
    (uint32_t)integerPrimTypeName,
    (uint32_t)bytePrimTypeName,
};

const uint32_t baseConstUtf8HashIndex8[] = {
    2,
    (uint32_t)systemClassName,
    (uint32_t)cloneNotSupportedExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex9[] = {
    1,
    (uint32_t)threadClassName,
};

const uint32_t baseConstUtf8HashIndex12[] = {
    5,
    (uint32_t)arrayStoreExceptionClassName,
    (uint32_t)floatPrimTypeName,
    (uint32_t)booleanPrimTypeName,
    (uint32_t)exceptionTypesFieldName,
    (uint32_t)mathClassName,
};

const uint32_t baseConstUtf8HashIndex13[] = {
    2,
    (uint32_t)negativeArraySizeExceptionClassName,
    (uint32_t)classNotFoundExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex16[] = {
    1,
    (uint32_t)unsupportedOperationExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex18[] = {
    2,
    (uint32_t)ioExceptionClassName,
    (uint32_t)flintGraphicsClassName,
};

const uint32_t baseConstUtf8HashIndex19[] = {
    2,
    (uint32_t)charPrimTypeName,
    (uint32_t)shortClassName,
};

const uint32_t baseConstUtf8HashIndex20[] = {
    1,
    (uint32_t)objectClassName,
};

const uint32_t baseConstUtf8HashIndex23[] = {
    3,
    (uint32_t)floatClassName,
    (uint32_t)exceptionClassName,
    (uint32_t)classCastExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex24[] = {
    2,
    (uint32_t)printStreamClassName,
    (uint32_t)characterClassName,
};

const uint32_t baseConstUtf8HashIndex25[] = {
    1,
    (uint32_t)arithmeticExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex26[] = {
    1,
    (uint32_t)doubleClassName,
};

const uint32_t baseConstUtf8HashIndex30[] = {
    2,
    (uint32_t)parameterTypesFieldName,
    (uint32_t)staticConstructorName,
};

const uint32_t baseConstUtf8HashIndex31[] = {
    2,
    (uint32_t)illegalArgumentExceptionClassName,
    (uint32_t)modifiersFieldName,
};

const uint32_t baseConstUtf8HashIndex34[] = {
    1,
    (uint32_t)fieldClassName,
};

const uint32_t baseConstUtf8HashIndex35[] = {
    1,
    (uint32_t)interruptedExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex36[] = {
    2,
    (uint32_t)booleanClassName,
    (uint32_t)constructorClassName,
};

const uint32_t baseConstUtf8HashIndex37[] = {
    2,
    (uint32_t)methodClassName,
    (uint32_t)classFormatErrorExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex38[] = {
    1,
    (uint32_t)arrayClassName,
};

const uint32_t baseConstUtf8HashIndex40[] = {
    1,
    (uint32_t)longClassName,
};

const uint32_t baseConstUtf8HashIndex41[] = {
    1,
    (uint32_t)noSuchMethodErrorExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex42[] = {
    1,
    (uint32_t)voidPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex43[] = {
    2,
    (uint32_t)arrayIndexOutOfBoundsExceptionClassName,
    (uint32_t)longPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex45[] = {
    2,
    (uint32_t)byteClassName,
    (uint32_t)unsatisfiedLinkErrorClassName,
};

const uint32_t baseConstUtf8HashIndex49[] = {
    2,
    (uint32_t)integerClassName,
    (uint32_t)shortPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex50[] = {
    1,
    (uint32_t)errorClassName,
};

const uint32_t baseConstUtf8HashIndex51[] = {
    2,
    (uint32_t)nameFieldName,
    (uint32_t)doublePrimTypeName,
};

const uint32_t baseConstUtf8HashIndex53[] = {
    3,
    (uint32_t)typeFieldName,
    (uint32_t)noSuchFieldErrorExceptionClassName,
    (uint32_t)constructorName,
};

const uint32_t baseConstUtf8HashIndex56[] = {
    2,
    (uint32_t)nullPointerExceptionClassName,
    (uint32_t)classClassName,
};

const ConstNameBaseList * const baseConstUtf8HashTable[57] = {
    [0] = 0,
    [1] = 0,
    [2] = (const ConstNameBaseList *)baseConstUtf8HashIndex2,
    [3] = 0,
    [4] = (const ConstNameBaseList *)baseConstUtf8HashIndex4,
    [5] = (const ConstNameBaseList *)baseConstUtf8HashIndex5,
    [6] = 0,
    [7] = (const ConstNameBaseList *)baseConstUtf8HashIndex7,
    [8] = (const ConstNameBaseList *)baseConstUtf8HashIndex8,
    [9] = (const ConstNameBaseList *)baseConstUtf8HashIndex9,
    [10] = 0,
    [11] = 0,
    [12] = (const ConstNameBaseList *)baseConstUtf8HashIndex12,
    [13] = (const ConstNameBaseList *)baseConstUtf8HashIndex13,
    [14] = 0,
    [15] = 0,
    [16] = (const ConstNameBaseList *)baseConstUtf8HashIndex16,
    [17] = 0,
    [18] = (const ConstNameBaseList *)baseConstUtf8HashIndex18,
    [19] = (const ConstNameBaseList *)baseConstUtf8HashIndex19,
    [20] = (const ConstNameBaseList *)baseConstUtf8HashIndex20,
    [21] = 0,
    [22] = 0,
    [23] = (const ConstNameBaseList *)baseConstUtf8HashIndex23,
    [24] = (const ConstNameBaseList *)baseConstUtf8HashIndex24,
    [25] = (const ConstNameBaseList *)baseConstUtf8HashIndex25,
    [26] = (const ConstNameBaseList *)baseConstUtf8HashIndex26,
    [27] = 0,
    [28] = 0,
    [29] = 0,
    [30] = (const ConstNameBaseList *)baseConstUtf8HashIndex30,
    [31] = (const ConstNameBaseList *)baseConstUtf8HashIndex31,
    [32] = 0,
    [33] = 0,
    [34] = (const ConstNameBaseList *)baseConstUtf8HashIndex34,
    [35] = (const ConstNameBaseList *)baseConstUtf8HashIndex35,
    [36] = (const ConstNameBaseList *)baseConstUtf8HashIndex36,
    [37] = (const ConstNameBaseList *)baseConstUtf8HashIndex37,
    [38] = (const ConstNameBaseList *)baseConstUtf8HashIndex38,
    [39] = 0,
    [40] = (const ConstNameBaseList *)baseConstUtf8HashIndex40,
    [41] = (const ConstNameBaseList *)baseConstUtf8HashIndex41,
    [42] = (const ConstNameBaseList *)baseConstUtf8HashIndex42,
    [43] = (const ConstNameBaseList *)baseConstUtf8HashIndex43,
    [44] = 0,
    [45] = (const ConstNameBaseList *)baseConstUtf8HashIndex45,
    [46] = 0,
    [47] = 0,
    [48] = 0,
    [49] = (const ConstNameBaseList *)baseConstUtf8HashIndex49,
    [50] = (const ConstNameBaseList *)baseConstUtf8HashIndex50,
    [51] = (const ConstNameBaseList *)baseConstUtf8HashIndex51,
    [52] = 0,
    [53] = (const ConstNameBaseList *)baseConstUtf8HashIndex53,
    [54] = 0,
    [55] = 0,
    [56] = (const ConstNameBaseList *)baseConstUtf8HashIndex56,
};
