/*
 * This file was generated by FlintBuildTool.
 * Please do not edit/update this file manually.
 */

#include "flint_const_name_base.h"
#include "flint_const_name_base_hash_table.h"

const uint32_t baseConstUtf8HashIndex0[] = {
    2,
    (uint32_t)&typeFieldName,
    (uint32_t)&staticConstructorName,
};

const uint32_t baseConstUtf8HashIndex1[] = {
    2,
    (uint32_t)&integerPrimTypeName,
    (uint32_t)&shortClassName,
};

const uint32_t baseConstUtf8HashIndex2[] = {
    2,
    (uint32_t)&fieldClassName,
    (uint32_t)&bigIntegerClassName,
};

const uint32_t baseConstUtf8HashIndex3[] = {
    3,
    (uint32_t)&stringClassName,
    (uint32_t)&cloneNotSupportedExceptionClassName,
    (uint32_t)&parameterTypesFieldName,
};

const uint32_t baseConstUtf8HashIndex6[] = {
    1,
    (uint32_t)&constructorClassName,
};

const uint32_t baseConstUtf8HashIndex8[] = {
    3,
    (uint32_t)&voidPrimTypeName,
    (uint32_t)&doublePrimTypeName,
    (uint32_t)&classClassName,
};

const uint32_t baseConstUtf8HashIndex9[] = {
    1,
    (uint32_t)&clazzFieldName,
};

const uint32_t baseConstUtf8HashIndex11[] = {
    1,
    (uint32_t)&ioExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex13[] = {
    1,
    (uint32_t)&byteClassName,
};

const uint32_t baseConstUtf8HashIndex15[] = {
    3,
    (uint32_t)&modifiersFieldName,
    (uint32_t)&mathClassName,
    (uint32_t)&nullPointerExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex16[] = {
    2,
    (uint32_t)&arrayIndexOutOfBoundsExceptionClassName,
    (uint32_t)&shortPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex18[] = {
    2,
    (uint32_t)&arrayStoreExceptionClassName,
    (uint32_t)&characterClassName,
};

const uint32_t baseConstUtf8HashIndex20[] = {
    1,
    (uint32_t)&flintGraphicsClassName,
};

const uint32_t baseConstUtf8HashIndex22[] = {
    2,
    (uint32_t)&errorClassName,
    (uint32_t)&returnTypeFieldName,
};

const uint32_t baseConstUtf8HashIndex24[] = {
    1,
    (uint32_t)&systemClassName,
};

const uint32_t baseConstUtf8HashIndex25[] = {
    1,
    (uint32_t)&floatPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex28[] = {
    2,
    (uint32_t)&doubleClassName,
    (uint32_t)&longClassName,
};

const uint32_t baseConstUtf8HashIndex29[] = {
    2,
    (uint32_t)&integerClassName,
    (uint32_t)&classNotFoundExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex30[] = {
    1,
    (uint32_t)&noSuchMethodErrorExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex31[] = {
    1,
    (uint32_t)&negativeArraySizeExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex32[] = {
    1,
    (uint32_t)&bytePrimTypeName,
};

const uint32_t baseConstUtf8HashIndex33[] = {
    3,
    (uint32_t)&longPrimTypeName,
    (uint32_t)&charPrimTypeName,
    (uint32_t)&arithmeticExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex36[] = {
    1,
    (uint32_t)&constructorName,
};

const uint32_t baseConstUtf8HashIndex38[] = {
    1,
    (uint32_t)&unsupportedOperationExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex39[] = {
    3,
    (uint32_t)&methodClassName,
    (uint32_t)&throwableClassName,
    (uint32_t)&unsatisfiedLinkErrorClassName,
};

const uint32_t baseConstUtf8HashIndex40[] = {
    1,
    (uint32_t)&floatClassName,
};

const uint32_t baseConstUtf8HashIndex41[] = {
    2,
    (uint32_t)&interruptedExceptionClassName,
    (uint32_t)&classCastExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex43[] = {
    1,
    (uint32_t)&objectClassName,
};

const uint32_t baseConstUtf8HashIndex45[] = {
    1,
    (uint32_t)&arrayClassName,
};

const uint32_t baseConstUtf8HashIndex46[] = {
    1,
    (uint32_t)&nameFieldName,
};

const uint32_t baseConstUtf8HashIndex48[] = {
    1,
    (uint32_t)&booleanPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex51[] = {
    1,
    (uint32_t)&booleanClassName,
};

const uint32_t baseConstUtf8HashIndex52[] = {
    1,
    (uint32_t)&printStreamClassName,
};

const uint32_t baseConstUtf8HashIndex53[] = {
    2,
    (uint32_t)&illegalArgumentExceptionClassName,
    (uint32_t)&exceptionTypesFieldName,
};

const uint32_t baseConstUtf8HashIndex54[] = {
    2,
    (uint32_t)&threadClassName,
    (uint32_t)&exceptionClassName,
};

const ConstNameBaseList * const baseConstUtf8HashTable[56] = {
    [0] = (const ConstNameBaseList *)baseConstUtf8HashIndex0,
    [1] = (const ConstNameBaseList *)baseConstUtf8HashIndex1,
    [2] = (const ConstNameBaseList *)baseConstUtf8HashIndex2,
    [3] = (const ConstNameBaseList *)baseConstUtf8HashIndex3,
    [4] = 0,
    [5] = 0,
    [6] = (const ConstNameBaseList *)baseConstUtf8HashIndex6,
    [7] = 0,
    [8] = (const ConstNameBaseList *)baseConstUtf8HashIndex8,
    [9] = (const ConstNameBaseList *)baseConstUtf8HashIndex9,
    [10] = 0,
    [11] = (const ConstNameBaseList *)baseConstUtf8HashIndex11,
    [12] = 0,
    [13] = (const ConstNameBaseList *)baseConstUtf8HashIndex13,
    [14] = 0,
    [15] = (const ConstNameBaseList *)baseConstUtf8HashIndex15,
    [16] = (const ConstNameBaseList *)baseConstUtf8HashIndex16,
    [17] = 0,
    [18] = (const ConstNameBaseList *)baseConstUtf8HashIndex18,
    [19] = 0,
    [20] = (const ConstNameBaseList *)baseConstUtf8HashIndex20,
    [21] = 0,
    [22] = (const ConstNameBaseList *)baseConstUtf8HashIndex22,
    [23] = 0,
    [24] = (const ConstNameBaseList *)baseConstUtf8HashIndex24,
    [25] = (const ConstNameBaseList *)baseConstUtf8HashIndex25,
    [26] = 0,
    [27] = 0,
    [28] = (const ConstNameBaseList *)baseConstUtf8HashIndex28,
    [29] = (const ConstNameBaseList *)baseConstUtf8HashIndex29,
    [30] = (const ConstNameBaseList *)baseConstUtf8HashIndex30,
    [31] = (const ConstNameBaseList *)baseConstUtf8HashIndex31,
    [32] = (const ConstNameBaseList *)baseConstUtf8HashIndex32,
    [33] = (const ConstNameBaseList *)baseConstUtf8HashIndex33,
    [34] = 0,
    [35] = 0,
    [36] = (const ConstNameBaseList *)baseConstUtf8HashIndex36,
    [37] = 0,
    [38] = (const ConstNameBaseList *)baseConstUtf8HashIndex38,
    [39] = (const ConstNameBaseList *)baseConstUtf8HashIndex39,
    [40] = (const ConstNameBaseList *)baseConstUtf8HashIndex40,
    [41] = (const ConstNameBaseList *)baseConstUtf8HashIndex41,
    [42] = 0,
    [43] = (const ConstNameBaseList *)baseConstUtf8HashIndex43,
    [44] = 0,
    [45] = (const ConstNameBaseList *)baseConstUtf8HashIndex45,
    [46] = (const ConstNameBaseList *)baseConstUtf8HashIndex46,
    [47] = 0,
    [48] = (const ConstNameBaseList *)baseConstUtf8HashIndex48,
    [49] = 0,
    [50] = 0,
    [51] = (const ConstNameBaseList *)baseConstUtf8HashIndex51,
    [52] = (const ConstNameBaseList *)baseConstUtf8HashIndex52,
    [53] = (const ConstNameBaseList *)baseConstUtf8HashIndex53,
    [54] = (const ConstNameBaseList *)baseConstUtf8HashIndex54,
    [55] = 0,
};
