/*
 * This file was generated by FlintBuildTool.
 * Please do not edit/update this file manually.
 */

#include "flint_const_name_base.h"
#include "flint_const_name_base_hash_table.h"

const uint32_t baseConstUtf8HashIndex2[] = {
    1,
    (uint32_t)doublePrimTypeName,
};

const uint32_t baseConstUtf8HashIndex3[] = {
    1,
    (uint32_t)arrayClassName,
};

const uint32_t baseConstUtf8HashIndex4[] = {
    2,
    (uint32_t)printStreamClassName,
    (uint32_t)bytePrimTypeName,
};

const uint32_t baseConstUtf8HashIndex5[] = {
    1,
    (uint32_t)objectClassName,
};

const uint32_t baseConstUtf8HashIndex6[] = {
    1,
    (uint32_t)systemClassName,
};

const uint32_t baseConstUtf8HashIndex7[] = {
    1,
    (uint32_t)longPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex9[] = {
    1,
    (uint32_t)shortClassName,
};

const uint32_t baseConstUtf8HashIndex10[] = {
    1,
    (uint32_t)fieldClassName,
};

const uint32_t baseConstUtf8HashIndex11[] = {
    1,
    (uint32_t)floatPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex12[] = {
    2,
    (uint32_t)arrayStoreExceptionClassName,
    (uint32_t)nameFieldName,
};

const uint32_t baseConstUtf8HashIndex13[] = {
    1,
    (uint32_t)integerClassName,
};

const uint32_t baseConstUtf8HashIndex15[] = {
    2,
    (uint32_t)illegalArgumentExceptionClassName,
    (uint32_t)nullPointerExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex16[] = {
    2,
    (uint32_t)classFormatErrorExceptionClassName,
    (uint32_t)noSuchMethodErrorExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex17[] = {
    2,
    (uint32_t)charPrimTypeName,
    (uint32_t)unsatisfiedLinkErrorClassName,
};

const uint32_t baseConstUtf8HashIndex18[] = {
    2,
    (uint32_t)arrayIndexOutOfBoundsExceptionClassName,
    (uint32_t)longClassName,
};

const uint32_t baseConstUtf8HashIndex20[] = {
    1,
    (uint32_t)bigIntegerClassName,
};

const uint32_t baseConstUtf8HashIndex21[] = {
    2,
    (uint32_t)stringClassName,
    (uint32_t)modifiersFieldName,
};

const uint32_t baseConstUtf8HashIndex24[] = {
    2,
    (uint32_t)floatClassName,
    (uint32_t)classClassName,
};

const uint32_t baseConstUtf8HashIndex25[] = {
    3,
    (uint32_t)throwableClassName,
    (uint32_t)byteClassName,
    (uint32_t)integerPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex26[] = {
    1,
    (uint32_t)exceptionClassName,
};

const uint32_t baseConstUtf8HashIndex30[] = {
    2,
    (uint32_t)errorClassName,
    (uint32_t)constructorClassName,
};

const uint32_t baseConstUtf8HashIndex31[] = {
    2,
    (uint32_t)parameterTypesFieldName,
    (uint32_t)negativeArraySizeExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex33[] = {
    1,
    (uint32_t)booleanClassName,
};

const uint32_t baseConstUtf8HashIndex35[] = {
    4,
    (uint32_t)methodClassName,
    (uint32_t)noSuchFieldErrorExceptionClassName,
    (uint32_t)arithmeticExceptionClassName,
    (uint32_t)clazzFieldName,
};

const uint32_t baseConstUtf8HashIndex37[] = {
    1,
    (uint32_t)classNotFoundExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex39[] = {
    1,
    (uint32_t)ioExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex40[] = {
    2,
    (uint32_t)doubleClassName,
    (uint32_t)voidPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex41[] = {
    1,
    (uint32_t)mathClassName,
};

const uint32_t baseConstUtf8HashIndex42[] = {
    3,
    (uint32_t)characterClassName,
    (uint32_t)flintGraphicsClassName,
    (uint32_t)staticConstructorName,
};

const uint32_t baseConstUtf8HashIndex43[] = {
    1,
    (uint32_t)cloneNotSupportedExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex45[] = {
    1,
    (uint32_t)classCastExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex46[] = {
    1,
    (uint32_t)shortPrimTypeName,
};

const uint32_t baseConstUtf8HashIndex52[] = {
    1,
    (uint32_t)constructorName,
};

const uint32_t baseConstUtf8HashIndex53[] = {
    1,
    (uint32_t)interruptedExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex54[] = {
    4,
    (uint32_t)typeFieldName,
    (uint32_t)returnTypeFieldName,
    (uint32_t)booleanPrimTypeName,
    (uint32_t)threadClassName,
};

const uint32_t baseConstUtf8HashIndex56[] = {
    1,
    (uint32_t)unsupportedOperationExceptionClassName,
};

const uint32_t baseConstUtf8HashIndex57[] = {
    1,
    (uint32_t)exceptionTypesFieldName,
};

const ConstNameBaseList * const baseConstUtf8HashTable[58] = {
    [0] = 0,
    [1] = 0,
    [2] = (const ConstNameBaseList *)baseConstUtf8HashIndex2,
    [3] = (const ConstNameBaseList *)baseConstUtf8HashIndex3,
    [4] = (const ConstNameBaseList *)baseConstUtf8HashIndex4,
    [5] = (const ConstNameBaseList *)baseConstUtf8HashIndex5,
    [6] = (const ConstNameBaseList *)baseConstUtf8HashIndex6,
    [7] = (const ConstNameBaseList *)baseConstUtf8HashIndex7,
    [8] = 0,
    [9] = (const ConstNameBaseList *)baseConstUtf8HashIndex9,
    [10] = (const ConstNameBaseList *)baseConstUtf8HashIndex10,
    [11] = (const ConstNameBaseList *)baseConstUtf8HashIndex11,
    [12] = (const ConstNameBaseList *)baseConstUtf8HashIndex12,
    [13] = (const ConstNameBaseList *)baseConstUtf8HashIndex13,
    [14] = 0,
    [15] = (const ConstNameBaseList *)baseConstUtf8HashIndex15,
    [16] = (const ConstNameBaseList *)baseConstUtf8HashIndex16,
    [17] = (const ConstNameBaseList *)baseConstUtf8HashIndex17,
    [18] = (const ConstNameBaseList *)baseConstUtf8HashIndex18,
    [19] = 0,
    [20] = (const ConstNameBaseList *)baseConstUtf8HashIndex20,
    [21] = (const ConstNameBaseList *)baseConstUtf8HashIndex21,
    [22] = 0,
    [23] = 0,
    [24] = (const ConstNameBaseList *)baseConstUtf8HashIndex24,
    [25] = (const ConstNameBaseList *)baseConstUtf8HashIndex25,
    [26] = (const ConstNameBaseList *)baseConstUtf8HashIndex26,
    [27] = 0,
    [28] = 0,
    [29] = 0,
    [30] = (const ConstNameBaseList *)baseConstUtf8HashIndex30,
    [31] = (const ConstNameBaseList *)baseConstUtf8HashIndex31,
    [32] = 0,
    [33] = (const ConstNameBaseList *)baseConstUtf8HashIndex33,
    [34] = 0,
    [35] = (const ConstNameBaseList *)baseConstUtf8HashIndex35,
    [36] = 0,
    [37] = (const ConstNameBaseList *)baseConstUtf8HashIndex37,
    [38] = 0,
    [39] = (const ConstNameBaseList *)baseConstUtf8HashIndex39,
    [40] = (const ConstNameBaseList *)baseConstUtf8HashIndex40,
    [41] = (const ConstNameBaseList *)baseConstUtf8HashIndex41,
    [42] = (const ConstNameBaseList *)baseConstUtf8HashIndex42,
    [43] = (const ConstNameBaseList *)baseConstUtf8HashIndex43,
    [44] = 0,
    [45] = (const ConstNameBaseList *)baseConstUtf8HashIndex45,
    [46] = (const ConstNameBaseList *)baseConstUtf8HashIndex46,
    [47] = 0,
    [48] = 0,
    [49] = 0,
    [50] = 0,
    [51] = 0,
    [52] = (const ConstNameBaseList *)baseConstUtf8HashIndex52,
    [53] = (const ConstNameBaseList *)baseConstUtf8HashIndex53,
    [54] = (const ConstNameBaseList *)baseConstUtf8HashIndex54,
    [55] = 0,
    [56] = (const ConstNameBaseList *)baseConstUtf8HashIndex56,
    [57] = (const ConstNameBaseList *)baseConstUtf8HashIndex57,
};
